// Code generated by "stringer -type=Status"; DO NOT EDIT.

package chunker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PREDICATE-0]
	_ = x[SCALAR-1]
	_ = x[OBJECT-2]
	_ = x[ARRAY-3]
	_ = x[NONE-4]
}

const _Status_name = "PREDICATESCALAROBJECTARRAYNONE"

var _Status_index = [...]uint8{0, 9, 15, 21, 26, 30}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
